import Button from "./lib/components/Button";

export default function Home() {
  function click() {
    alert("clicked");
  }
  return (
    <div>
      <header>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </header>

      <body className={`ml-20 text-9xl`}>
        <h1 className="ml-20 text-9xl">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          <div className="text-sm">
            <Button
              value="0.1" //price of the item
              ownerAddress="0xE745C2Ab3A5D7CF284465F9F6c3Cb8E2f6a21fd4"
              chainId="137"
              label="Buy Now"
            />
          </div>
        </h1>
      </body>
    </div>
  );
}
